# Generated by Django 4.0 on 2022-01-15 21:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('952ee232-6484-4d9a-b000-1ad91ff717da'), primary_key=True, serialize=False),
        ),
    ]
