# Generated by Django 4.0 on 2022-01-16 23:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('caa1cddb-e5bf-4be4-b5a3-06f2bad3aec2'), primary_key=True, serialize=False),
        ),
    ]
