version: '3.1'

services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: korg1000
      POSTGRES_PASSWORD: korg1000
      POSTGRES_DB: todo

  backend:
    build:
      context: .
    ports:
      - 8080:8080
    command: bash -c "
      python manage.py migrate
      && python manage.py create_data
      && python manage.py runserver 0.0.0.0:8080
      "
    depends_on:
      - db


#  adminer:
#    image: adminer:4.7.8-standalone
#    restart: always
#    ports:
#      - 8080:8080
#    depends_on:
#      - db
